var annotated_dup =
[
    [ "ai_core", "namespaceai__core.html", "namespaceai__core" ],
    [ "ai_DLLib_wrapper", "namespaceai___d_l_lib__wrapper.html", "namespaceai___d_l_lib__wrapper" ],
    [ "ai_function_wrapper", "namespaceai__function__wrapper.html", "namespaceai__function__wrapper" ],
    [ "ai_handle_response", "namespaceai__handle__response.html", "namespaceai__handle__response" ],
    [ "ai_strategy_management", "namespaceai__strategy__management.html", "namespaceai__strategy__management" ],
    [ "gui", "namespacegui.html", "namespacegui" ],
    [ "argument_s", "structargument__s.html", "structargument__s" ],
    [ "broadcast_data_s", "structbroadcast__data__s.html", "structbroadcast__data__s" ],
    [ "command_data_s", "structcommand__data__s.html", "structcommand__data__s" ],
    [ "container_s", "structcontainer__s.html", "structcontainer__s" ],
    [ "egg_s", "structegg__s.html", "structegg__s" ],
    [ "entity_diff_s", "structentity__diff__s.html", "structentity__diff__s" ],
    [ "entity_s", "structentity__s.html", "structentity__s" ],
    [ "entity_wrapper_s", "structentity__wrapper__s.html", "structentity__wrapper__s" ],
    [ "Event", "class_event.html", "class_event" ],
    [ "generate_s", "structgenerate__s.html", "structgenerate__s" ],
    [ "incantation_level_s", "structincantation__level__s.html", "structincantation__level__s" ],
    [ "map_s", "structmap__s.html", "structmap__s" ],
    [ "peer_s", "structpeer__s.html", "structpeer__s" ],
    [ "player_list_s", "structplayer__list__s.html", "structplayer__list__s" ],
    [ "player_s", "structplayer__s.html", "structplayer__s" ],
    [ "position_s", "structposition__s.html", "structposition__s" ],
    [ "retcodes_s", "structretcodes__s.html", "structretcodes__s" ],
    [ "scheduler_event_s", "structscheduler__event__s.html", "structscheduler__event__s" ],
    [ "scheduler_s", "structscheduler__s.html", "structscheduler__s" ],
    [ "server_data_s", "structserver__data__s.html", "structserver__data__s" ],
    [ "server_s", "structserver__s.html", "structserver__s" ],
    [ "tcp_server_s", "structtcp__server__s.html", "structtcp__server__s" ],
    [ "team_s", "structteam__s.html", "structteam__s" ],
    [ "tile_s", "structtile__s.html", "structtile__s" ],
    [ "zappy_client_s", "structzappy__client__s.html", "structzappy__client__s" ],
    [ "zappy_server_s", "structzappy__server__s.html", "structzappy__server__s" ]
];