var dir_94cd27059878c2af96951ddf2b1d58a4 =
[
    [ "auth_command.c", "auth__command_8c.html", "auth__command_8c" ],
    [ "broadcast_command.c", "broadcast__command_8c.html", "broadcast__command_8c" ],
    [ "broadcast_process.c", "broadcast__process_8c.html", "broadcast__process_8c" ],
    [ "connectnbr_command.c", "connectnbr__command_8c.html", "connectnbr__command_8c" ],
    [ "eject_command.c", "eject__command_8c.html", "eject__command_8c" ],
    [ "eject_process.c", "eject__process_8c.html", "eject__process_8c" ],
    [ "entity_info.c", "entity__info_8c.html", "entity__info_8c" ],
    [ "fork_command.c", "fork__command_8c.html", "fork__command_8c" ],
    [ "fork_utils.c", "fork__utils_8c.html", "fork__utils_8c" ],
    [ "forward_command.c", "forward__command_8c.html", "forward__command_8c" ],
    [ "game_status.c", "game__status_8c.html", "game__status_8c" ],
    [ "incantation_command.c", "incantation__command_8c.html", "incantation__command_8c" ],
    [ "inventory_command.c", "inventory__command_8c.html", "inventory__command_8c" ],
    [ "join_command.c", "join__command_8c.html", "join__command_8c" ],
    [ "look_command.c", "look__command_8c.html", "look__command_8c" ],
    [ "look_process.c", "look__process_8c.html", "look__process_8c" ],
    [ "look_utils.c", "look__utils_8c.html", "look__utils_8c" ],
    [ "map_info.c", "map__info_8c.html", "map__info_8c" ],
    [ "place_command.c", "place__command_8c.html", "place__command_8c" ],
    [ "start_information.c", "start__information_8c.html", "start__information_8c" ],
    [ "take_command.c", "take__command_8c.html", "take__command_8c" ],
    [ "turn_command.c", "turn__command_8c.html", "turn__command_8c" ],
    [ "unexpected_send.c", "unexpected__send_8c.html", "unexpected__send_8c" ]
];