#!/usr/bin/python3
import sys

sys.path.append('../')

from ai_DLLib_wrapper import DLLibWrapper

def lib_test(lib_path : str) -> DLLibWrapper:
    """ Add the path to the lib in the LibWrapper Object """
    lib_object : DLLibWrapper = DLLibWrapper(lib_path)
    return lib_object

""" Main Function """
Test1 : DLLibWrapper = lib_test("./unexisting_lib.so")
try:
    Test1.openLibrary()
except Exception as e:
    assert(e.args == ('./unexisting_lib.so: cannot open shared object file: No such file or directory', ))
print("The first test for Lib Wrapper object is valid !")

Test2 : DLLibWrapper = lib_test("./../libzappy_ai_api.so")
try:
    Test2.openLibrary()
except:
    print("The second test for the Lib Wrapper has failed")
    exit()
Test2.closeLibray()
print("The second test for Lib Wrapper object is valid !")

Test3 : DLLibWrapper = lib_test("./TestLib.so")
try:
    Test3.openLibrary()
    ptr = Test3.getFunctionFromLibrary("malloc")
    Test3.closeLibray()
except:
    print("The third test for the Lib Wrapper has failed")
    exit()
assert(ptr != None)
print("The third test for the Lib Wrapper is valid !")

print("All the tests for the Lib Wrapper are valids !")