#!/usr/bin/python3
from multiprocessing.context import assert_spawning
from statistics import multimode
import sys

sys.path.append('../')

from ai_handle_response import Map, Tile

def map_test(test_str : str) -> Map:
    """ Transform a str in Map object """
    map_object : Map = Map(test_str)
    return map_object

""" Main Function """
Test1 : Map = map_test("player , , , thystame , , food , , , , , thystame , , , , , ,")
test_tile_1 : Tile = Test1.GetTile(0)
test_tile_2 : Tile = Test1.GetTile(3)
test_tile_3 : Tile = Test1.GetTile(5)
test_tile_4 : Tile = Test1.GetTile(10)
assert(test_tile_1.player == 1 and test_tile_2.thystame == 1 and test_tile_3.food == 1 and test_tile_4.thystame == 1)
print("The first test for the map object is valid !")

Test2 : Map = map_test("player , player deraumere , ,")
test_tile : Tile = Test2.GetTile(1)
assert(test_tile.player == 1 and test_tile.deraumere == 1)
print("The second test for the map object is valid !")

Test3 : Map = map_test("player player player deraumere deraumere food food food food food food ,")
multiple_test_tile : Tile = Test3.GetTile(0)
assert(multiple_test_tile.player == 3 and multiple_test_tile.deraumere == 2 and multiple_test_tile.food == 6)
print("The third test for the map object is valid !")

print("All the tests for the map object are valid !")