name: GCP Mirroring

on:
  push:
    branches: [ bonus/main ]
  delete:
    branches: [ bonus/main ]
  workflow_dispatch:
    branches: [ bonus/main ]

jobs:
  to_GCP:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EPI_MIRRORING_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          export GIT_SSH_CMD = "ssh -v -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p 2022 -l cavonstavant"
          git remote add mirror "cavonstavant@gmail.com@source.developers.google.com:2022/p/zappy-355118/r/ZAAAAAAAAAAAAppy"
          git push --tags --force --prune mirror "refs/remotes/origin/*:refs/heads/*"
