name: GCP Mirroring

on:
  push:
    branches: [ bonus/main ]
  delete:
    branches: [ bonus/main ]
  workflow_dispatch:
    branches: [ bonus/main ]

jobs:
  to_GCP:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            cavonstavant@gmail.com@source.developers.google.com:2022/p/zappy-355118/r/ZAAAAAAAAAAAAppy
          ssh_private_key:
            ${{ secrets.EPI_MIRRORING_KEY }}
          ssh_username:
            cavonstavant
